### ISSUE TITLE
Help with gui

### ISSUE THREAD

**Issue by jdmandsc-ff** [AdvancedMacros/AdvancedMacros#11]
Hello. Can you show me actual gui example? Thanks

**Comment by TheIncgi** [comment]
**If you are talking about making a gui**
Added this page, in it the editor zip has a simple gui (classWizard.lua)
and a more complex one (launched from Init.lua)
https://sites.google.com/site/advancedmacrosdocumentation/examples/large-examples

Additionally, the in-game change log is made using a script as well
https://github.com/TheIncgi/AdvancedMacros-Source/blob/master/src/main/resources/assets/advancedmacros/scripts/changelogviewer.lua

In a nutshell, a gui has 'child' elements where any events (keyboard or mouse) are passed to each element until the event is consumed
You can create new elements with:
newBox(<x,y,wid,hei,thickness>)
newGroup()
newImage(<texture, x, y, wid, hei>)
newItem(String: itemID <x, y, count>)
newMinecraftTextField(<x,y,wid,hei,text>)
newRectangle( <x, y, wid, hei> )
newScrollbar(<x, y, wid, len, orientation>) --vertical/vert/v or horizontal/horiz/h
newText(<text, x, y>)
newTextArea(<x,y,wid,hei,text>) --like mods text editor
all of those functions are in the table returned by gui.new()
every element, and the gui itself will have functions to let you set callbacks for different events
keyboard events are either
{keycode, scancode, modifiers}
or
{char, modifiers} --charTyped only
mouse events provide x,y,mouseButton

and yourGui.open() will show you the gui


**If instead you meant you wanted to interact with a gui, like say move an item from one slot to another**
This example crafts iron ingots into blocks using a crafting table as soon as it is opened
(binding set to GuiOpen Event)
https://pastebin.com/mSCPmpHa

The gui event also provides controls for interacting with things like anvils (set the name, get repair cost) enchanting tables, books, and some other common gui's (should be all the vanilla ones)
