### ISSUE TITLE
Chat messages from other Forge mods doesn't fire "Chat" event.

### ISSUE THREAD

**Issue by MajsterTynek** [AdvancedMacros/AdvancedMacros#13]
When some other Forge mode writes to chat "Chat" event is not invoked.
![image](https://user-images.githubusercontent.com/13304376/68446818-27c7e280-01de-11ea-9325-ffdf75297dea.png)

**Comment by MajsterTynek** [comment]
I have made a wourkaround library `barilog.lua`: 
[(available on AdvancedMacros discord)](https://discord.com/channels/473440074047160331/707597339979808859/767168938273931296)
![image](https://user-images.githubusercontent.com/13304376/96355482-6d757680-10e2-11eb-91a4-b7634f688352.png)

**Comment by TheIncgi** [comment]
If I remember correctly, this was fixed.
When the chat filter event triggered it use to consume the event.
Code should cause any remaining listeners to be fired so it should work as normal.
If there's another issue or this isn't fixed on a specific version:
 - link to this issue
 - label with versions that need fixing
