### ISSUE TITLE
getPlayer() crashes the game

### ISSUE THREAD

**Issue by Qonsyuma** [AdvancedMacros/AdvancedMacros#9]
An example script is:
while true do getPlayer() end

This is an extreme example, but often enough an updated value of Hunger, Health, Inventory, Block looked etc. is what's needed, and because of this bug it quickly gets fairly annoying to have scripts running.

( This seems to happen more often when the player is wearing armor )

**Comment by TheIncgi** [comment]
Late reply:
Caused by a ConcurrentModificationException I'd guess

Current workaround is to use `runOnMC(getPlayer)` or `runOnMC(getPlayer, "playerName")`
